name: Stage2

on:
  workflow_run:
    workflows: ["Stage1"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Build started"

      - name: Install Python
        run: bash ./install.sh
